"""File generators package."""

from .base import BaseGenerator, GeneratedFile
from .image_generator import (
    CorruptPNG,
    CorruptJPEG,
    LargeMetadataImage,
    WrongMIMEImage,
    EmptyImage,
    GiantImage,
)
from .document_generator import (
    EdgeCasePDF,
    MalformedSVG,
    LargePDF,
    PDFWithJavaScript,
    RTFWithEmbedded,
)
from .archive_generator import (
    CorruptZIP,
    ZipSlipArchive,
    LargeArchive,
    EmptyArchive,
    SymlinkArchive,
    BombZIP,
)
from .mixed_generator import (
    TextInBinary,
    DoubleExtensionFile,
    NullByteInjection,
    PolyglotFile,
    HTMLinImage,
    LongFilename,
    UnicodeFilenames,
)
from .executable_generator import (
    FakeEXE,
    FakeELF,
    MacroEnabledDOCX,
    MacroEnabledXLSX,
    ODTFile,
    GzipBomb,
    SevenZipArchive,
    RARArchive,
)
from .extended_generator import (
    PPTMacro,
    XLSMBom,
    OfficeOXMLExternalEntity,
    WordWithEmbeddedHTML,
    XZBomb,
    NestedArchiveBomb,
    DEFLATEBomb,
    SevenZipSolidArchive,
    BZ2Bomb,
    LZ4Bomb,
    WebShellArchive,
    LargeJSONFile,
    XMLBomb,
)

__all__ = [
    "BaseGenerator",
    "GeneratedFile",
    "CorruptPNG",
    "CorruptJPEG",
    "LargeMetadataImage",
    "WrongMIMEImage",
    "EmptyImage",
    "GiantImage",
    "EdgeCasePDF",
    "MalformedSVG",
    "LargePDF",
    "PDFWithJavaScript",
    "RTFWithEmbedded",
    "CorruptZIP",
    "ZipSlipArchive",
    "LargeArchive",
    "EmptyArchive",
    "SymlinkArchive",
    "BombZIP",
    "TextInBinary",
    "DoubleExtensionFile",
    "NullByteInjection",
    "PolyglotFile",
    "HTMLinImage",
    "LongFilename",
    "UnicodeFilenames",
    "FakeEXE",
    "FakeELF",
    "MacroEnabledDOCX",
    "MacroEnabledXLSX",
    "ODTFile",
    "GzipBomb",
    "SevenZipArchive",
    "RARArchive",
    "PPTMacro",
    "XLSMBom",
    "OfficeOXMLExternalEntity",
    "WordWithEmbeddedHTML",
    "XZBomb",
    "NestedArchiveBomb",
    "DEFLATEBomb",
    "SevenZipSolidArchive",
    "BZ2Bomb",
    "LZ4Bomb",
    "WebShellArchive",
    "LargeJSONFile",
    "XMLBomb",
]
